
GET {{url}}/getLogin
###

GET {{url}}/getToken?code={{code}}
###

POST {{url}}/flashSets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name" : "FlashSet2"
}
###
GET {{url}}/flashSets
Authorization: Bearer {{token}}
