@flashSetId = 176412eb-207d-4ea5-baa5-b24803f80ed9
@flashCardId = 2

###################################

GET {{url}}/getLogin
###

GET {{url}}/token/{{refreshToken}}
###

###################################

GET {{url}}/flashSets
Authorization: Bearer {{token}}
###

GET {{url}}/flashSets/{{flashSetId}}
Authorization: Bearer {{token}}
###

POST {{url}}/flashSets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name" : "FlashSet16"
}
###

DELETE {{url}}/flashSets/{{flashSetId}}
Authorization: Bearer {{token}}
###

###################################

GET {{url}}/flashCards?flashSetId={{flashSetId}}
Authorization: Bearer {{token}}
###

POST {{url}}/flashCards
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "FlashSetId" : "{{flashSetId}}",
  "Question" : "Question2",
  "Answer" : "Answer7"
}
###

DELETE {{url}}/flashCards?flashSetId={{flashSetId}}&flashCardId={{flashCardId}}
Authorization: Bearer {{token}}
###

