@flashSetId = 4a6ab72d-e50c-4d75-89b6-c2b8fe49a73b
@flashCardId = 2

###################################

GET {{url}}/getLogin
###

GET {{url}}/token/{{refreshToken}}
###

###################################

GET {{url}}/flashSets
Authorization: Bearer {{token}}
###

GET {{url}}/flashSets/{{flashSetId}}
Authorization: Bearer {{token}}
###

POST {{url}}/flashSets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name" : "FlashSet3"
}
###

DELETE {{url}}/flashSets?flashSetId={{flashSetId}}
Authorization: Bearer {{token}}
###

###################################

GET {{url}}/flashCards?flashSetId={{flashSetId}}
Authorization: Bearer {{token}}
###

POST {{url}}/flashCards
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "FlashSetId" : "{{flashSetId}}",
  "Question" : "Question4",
  "Answer" : "Answer3"
}
###

DELETE {{url}}/flashCards?flashSetId={{flashSetId}}&flashCardId={{flashCardId}}
Authorization: Bearer {{token}}
###

