services:
  api:
    image: fiszkit.api
    container_name: api
    extends:
      file: docker-compose.override.yml
      service: api
    build:
      context: .
      dockerfile: FiszkIt.Api/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
